sudo: required
language: java

services:
  - docker

deploy:
  provider: heroku
  api_key:
    secure: ${API_HEROKU}
    app: lunchandlearnapp

before_install:
- docker pull mongo

script:
- make test
